# Generated by Django 6.0.7 on 2026-07-29 02:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_solicitud', models.CharField(choices=[('Recurso', 'Recurso'), ('Reparacion', 'Reparación')], default='Recurso', max_length=30)),
                ('cantidad_solicitada', models.IntegerField()),
                ('justificacion', models.CharField(max_length=500)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada'), ('Entregada', 'Entregada')], default='Pendiente', max_length=30)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('observaciones_resp', models.CharField(blank=True, max_length=500, null=True)),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='usuarios.escuela')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='inventario.item')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Recurso',
                'db_table': 'solicitud_recurso',
            },
        ),
    ]
