# Generated by Django 6.0.7 on 2026-07-28 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Categoría de Item',
                'db_table': 'categoria_item',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('unidad_medida', models.CharField(max_length=50)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventario.categoriaitem')),
            ],
            options={
                'verbose_name': 'Item',
                'db_table': 'item',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_total', models.IntegerField(default=0)),
                ('cantidad_bueno', models.IntegerField(default=0)),
                ('cantidad_regular', models.IntegerField(default=0)),
                ('cantidad_malo', models.IntegerField(default=0)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('observaciones', models.CharField(blank=True, max_length=500, null=True)),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='usuarios.escuela')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventarios', to='inventario.item')),
            ],
            options={
                'verbose_name': 'Inventario',
                'db_table': 'inventario',
            },
        ),
    ]
