# Generated by Django 6.0.7 on 2026-08-31 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Distribucion', '0001_initial'),
        ('Solicitudes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='distribucion',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distribuciones_solicitadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='distribucion',
            name='solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='distribuciones', to='Solicitudes.solicitudrecurso'),
        ),
    ]
