# Generated by Django 6.0.7 on 2026-07-29 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Infraestructura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('Aula', 'Aula'), ('Laboratorio', 'Laboratorio'), ('Oficina', 'Oficina'), ('Baño', 'Baño'), ('Cancha', 'Cancha'), ('Biblioteca', 'Biblioteca'), ('Comedor', 'Comedor')], max_length=100)),
                ('estado', models.CharField(choices=[('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Malo', 'Malo'), ('En reparacion', 'En reparación')], default='Bueno', max_length=30)),
                ('capacidad', models.IntegerField(blank=True, null=True)),
                ('año_construccion', models.IntegerField(blank=True, null=True)),
                ('area_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infraestructuras', to='usuarios.escuela')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infraestructuras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Infraestructura',
                'db_table': 'infraestructura',
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Electrico', 'Eléctrico'), ('Plomeria', 'Plomería'), ('Pintura', 'Pintura'), ('Estructural', 'Estructural'), ('Equipos', 'Equipos')], max_length=100)),
                ('descripcion', models.CharField(max_length=500)),
                ('prioridad', models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta'), ('Urgente', 'Urgente')], max_length=20)),
                ('estado', models.CharField(choices=[('Solicitado', 'Solicitado'), ('Programado', 'Programado'), ('En proceso', 'En proceso'), ('Completado', 'Completado')], default='Solicitado', max_length=30)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('costo_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='usuarios.escuela')),
                ('infraestructura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos', to='infraestructura.infraestructura')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'db_table': 'mantenimiento',
            },
        ),
    ]
