# Generated by Django 6.0.7 on 2026-08-27 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='departamento_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='usuarios.departamento'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('MINED', 'Centro MINED'), ('INATEC', 'Centro INATEC'), ('UNIVERSIDAD_PUBLICA', 'Universidad Pública'), ('UNIVERSIDAD_COMUNITARIA', 'Universidad Comunitaria'), ('ESCUELA_NORMAL', 'Escuela Normal'), ('OTRA', 'Otra institución pública')], default='MINED', max_length=50)),
                ('codigo', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=300)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('activa', models.BooleanField(default=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instituciones', to='usuarios.departamento')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instituciones', to='usuarios.municipio')),
            ],
            options={
                'db_table': 'institucion',
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='usuarios.institucion'),
        ),
    ]
