# Generated by Django 6.0.7 on 2026-08-28 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_departamento_asignado_alter_rol_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucion',
            name='tipo',
            field=models.CharField(choices=[('MINED', 'Centro MINED'), ('INATEC', 'Centro INATEC'), ('UNIVERSIDAD_PUBLICA', 'Universidad Pública'), ('UNIVERSIDAD_COMUNITARIA', 'Universidad Comunitaria'), ('ESCUELA_NORMAL', 'Escuela Normal'), ('SEDE_UNIVERSITARIA_PUBLICA', 'Sede universitaria pública'), ('OTRA_INSTITUCION_EDUCATIVA_PUBLICA', 'Otra institución educativa pública')], default='MINED', max_length=50),
        ),
    ]
