# Generated by Django 6.0.7 on 2026-07-29 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('solicitudes', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('Entrada', 'Entrada'), ('Salida', 'Salida')], default='Salida', max_length=20)),
                ('cantidad_enviada', models.IntegerField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Enviado', 'Enviado'), ('Recibido', 'Recibido'), ('Confirmado', 'Confirmado')], default='Enviado', max_length=30)),
                ('responsable_envio', models.CharField(blank=True, max_length=200, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=500, null=True)),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribuciones', to='usuarios.escuela')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distribuciones', to='inventario.item')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distribuciones', to='solicitudes.solicitudrecurso')),
            ],
            options={
                'verbose_name': 'Distribución',
                'db_table': 'distribucion',
            },
        ),
    ]
