# Generated by Django 6.0.7 on 2026-08-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_email', models.EmailField(blank=True, max_length=254)),
                ('usuario_nombre', models.CharField(blank=True, max_length=201)),
                ('rol', models.CharField(blank=True, max_length=50)),
                ('departamento', models.CharField(blank=True, max_length=100)),
                ('institucion', models.CharField(blank=True, max_length=200)),
                ('accion', models.CharField(max_length=30)),
                ('modulo', models.CharField(max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('objeto_id', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'registro_auditoria',
                'ordering': ['-fecha'],
            },
        ),
    ]
